server:
  port: 8083

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5434/payment_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuración de RabbitMQ (Consumidor)
  cloud:
    function:
      definition: processReservation # Debe coincidir con el nombre del @Bean en Java
    stream:
      bindings:
        # Canal de entrada (input del consumidor processReservation)
        processReservation-in-0:
          destination: ecoride-reservations # ¡Mismo Exchange que TripService!
          group: payment-group # Cola persistente para asegurar entrega
          content-type: application/json
        # SALIDA (Para enviar resultados)
        payment-out-0:
          destination: ecoride-payment-results # otro Exchange en Rabbit

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true