server:
  port: 8081

spring:
  application:
    name: trip-service
  datasource:
    url: jdbc:postgresql://localhost:5438/trip_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuración de RabbitMQ (Productor)
  cloud:
    stream:
      bindings:
        # Canal de salida para eventos de reserva
        reservation-out-0:
          destination: ecoride-reservations # Nombre del Exchange en Rabbit
          content-type: application/json
        # ENTRADA (Nuevo: Escuchar resultados de pagos)
        paymentResultProcessor-in-0:
          destination: ecoride-payment-results # Debe coincidir con el output de Payment
          group: trip-group

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true